// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_config.proto

#ifndef PROTOBUF_app_5fconfig_2eproto__INCLUDED
#define PROTOBUF_app_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_app_5fconfig_2eproto();
void protobuf_AssignDesc_app_5fconfig_2eproto();
void protobuf_ShutdownFile_app_5fconfig_2eproto();

class SimuShelfScan;

// ===================================================================

class SimuShelfScan : public ::google::protobuf::Message {
 public:
  SimuShelfScan();
  virtual ~SimuShelfScan();

  SimuShelfScan(const SimuShelfScan& from);

  inline SimuShelfScan& operator=(const SimuShelfScan& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SimuShelfScan& default_instance();

  void Swap(SimuShelfScan* other);

  // implements Message ----------------------------------------------

  SimuShelfScan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SimuShelfScan& from);
  void MergeFrom(const SimuShelfScan& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 ShelfNum = 2;
  inline int shelfnum_size() const;
  inline void clear_shelfnum();
  static const int kShelfNumFieldNumber = 2;
  inline ::google::protobuf::uint32 shelfnum(int index) const;
  inline void set_shelfnum(int index, ::google::protobuf::uint32 value);
  inline void add_shelfnum(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      shelfnum() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_shelfnum();

  // @@protoc_insertion_point(class_scope:SimuShelfScan)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > shelfnum_;
  friend void  protobuf_AddDesc_app_5fconfig_2eproto();
  friend void protobuf_AssignDesc_app_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_app_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static SimuShelfScan* default_instance_;
};
// ===================================================================


// ===================================================================

// SimuShelfScan

// repeated uint32 ShelfNum = 2;
inline int SimuShelfScan::shelfnum_size() const {
  return shelfnum_.size();
}
inline void SimuShelfScan::clear_shelfnum() {
  shelfnum_.Clear();
}
inline ::google::protobuf::uint32 SimuShelfScan::shelfnum(int index) const {
  // @@protoc_insertion_point(field_get:SimuShelfScan.ShelfNum)
  return shelfnum_.Get(index);
}
inline void SimuShelfScan::set_shelfnum(int index, ::google::protobuf::uint32 value) {
  shelfnum_.Set(index, value);
  // @@protoc_insertion_point(field_set:SimuShelfScan.ShelfNum)
}
inline void SimuShelfScan::add_shelfnum(::google::protobuf::uint32 value) {
  shelfnum_.Add(value);
  // @@protoc_insertion_point(field_add:SimuShelfScan.ShelfNum)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SimuShelfScan::shelfnum() const {
  // @@protoc_insertion_point(field_list:SimuShelfScan.ShelfNum)
  return shelfnum_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SimuShelfScan::mutable_shelfnum() {
  // @@protoc_insertion_point(field_mutable_list:SimuShelfScan.ShelfNum)
  return &shelfnum_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_app_5fconfig_2eproto__INCLUDED
