// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "app_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SimuShelfScan_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SimuShelfScan_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_app_5fconfig_2eproto() {
  protobuf_AddDesc_app_5fconfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "app_config.proto");
  GOOGLE_CHECK(file != NULL);
  SimuShelfScan_descriptor_ = file->message_type(0);
  static const int SimuShelfScan_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimuShelfScan, shelfnum_),
  };
  SimuShelfScan_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SimuShelfScan_descriptor_,
      SimuShelfScan::default_instance_,
      SimuShelfScan_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimuShelfScan, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimuShelfScan, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SimuShelfScan));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_app_5fconfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SimuShelfScan_descriptor_, &SimuShelfScan::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_app_5fconfig_2eproto() {
  delete SimuShelfScan::default_instance_;
  delete SimuShelfScan_reflection_;
}

void protobuf_AddDesc_app_5fconfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020app_config.proto\"!\n\rSimuShelfScan\022\020\n\010S"
    "helfNum\030\002 \003(\r", 53);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "app_config.proto", &protobuf_RegisterTypes);
  SimuShelfScan::default_instance_ = new SimuShelfScan();
  SimuShelfScan::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_app_5fconfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_app_5fconfig_2eproto {
  StaticDescriptorInitializer_app_5fconfig_2eproto() {
    protobuf_AddDesc_app_5fconfig_2eproto();
  }
} static_descriptor_initializer_app_5fconfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int SimuShelfScan::kShelfNumFieldNumber;
#endif  // !_MSC_VER

SimuShelfScan::SimuShelfScan()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SimuShelfScan)
}

void SimuShelfScan::InitAsDefaultInstance() {
}

SimuShelfScan::SimuShelfScan(const SimuShelfScan& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SimuShelfScan)
}

void SimuShelfScan::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SimuShelfScan::~SimuShelfScan() {
  // @@protoc_insertion_point(destructor:SimuShelfScan)
  SharedDtor();
}

void SimuShelfScan::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SimuShelfScan::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SimuShelfScan::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SimuShelfScan_descriptor_;
}

const SimuShelfScan& SimuShelfScan::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_app_5fconfig_2eproto();
  return *default_instance_;
}

SimuShelfScan* SimuShelfScan::default_instance_ = NULL;

SimuShelfScan* SimuShelfScan::New() const {
  return new SimuShelfScan;
}

void SimuShelfScan::Clear() {
  shelfnum_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SimuShelfScan::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SimuShelfScan)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 ShelfNum = 2;
      case 2: {
        if (tag == 16) {
         parse_ShelfNum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 16, input, this->mutable_shelfnum())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_shelfnum())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_ShelfNum;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SimuShelfScan)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SimuShelfScan)
  return false;
#undef DO_
}

void SimuShelfScan::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SimuShelfScan)
  // repeated uint32 ShelfNum = 2;
  for (int i = 0; i < this->shelfnum_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      2, this->shelfnum(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SimuShelfScan)
}

::google::protobuf::uint8* SimuShelfScan::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SimuShelfScan)
  // repeated uint32 ShelfNum = 2;
  for (int i = 0; i < this->shelfnum_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(2, this->shelfnum(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SimuShelfScan)
  return target;
}

int SimuShelfScan::ByteSize() const {
  int total_size = 0;

  // repeated uint32 ShelfNum = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->shelfnum_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->shelfnum(i));
    }
    total_size += 1 * this->shelfnum_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SimuShelfScan::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SimuShelfScan* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SimuShelfScan*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SimuShelfScan::MergeFrom(const SimuShelfScan& from) {
  GOOGLE_CHECK_NE(&from, this);
  shelfnum_.MergeFrom(from.shelfnum_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SimuShelfScan::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SimuShelfScan::CopyFrom(const SimuShelfScan& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimuShelfScan::IsInitialized() const {

  return true;
}

void SimuShelfScan::Swap(SimuShelfScan* other) {
  if (other != this) {
    shelfnum_.Swap(&other->shelfnum_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SimuShelfScan::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SimuShelfScan_descriptor_;
  metadata.reflection = SimuShelfScan_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
