// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compensation.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "compensation.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CBackLog_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CBackLog_reflection_ = NULL;
const ::google::protobuf::Descriptor* CServerPort_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CServerPort_reflection_ = NULL;
const ::google::protobuf::Descriptor* CAlarmInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CAlarmInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* CAlarmList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CAlarmList_reflection_ = NULL;
const ::google::protobuf::Descriptor* CCompInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CCompInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMcu_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMcu_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMcuList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMcuList_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_compensation_2eproto() {
  protobuf_AddDesc_compensation_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "compensation.proto");
  GOOGLE_CHECK(file != NULL);
  CBackLog_descriptor_ = file->message_type(0);
  static const int CBackLog_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CBackLog, uilogbacktime_),
  };
  CBackLog_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CBackLog_descriptor_,
      CBackLog::default_instance_,
      CBackLog_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CBackLog, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CBackLog, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CBackLog));
  CServerPort_descriptor_ = file->message_type(1);
  static const int CServerPort_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CServerPort, uiport_),
  };
  CServerPort_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CServerPort_descriptor_,
      CServerPort::default_instance_,
      CServerPort_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CServerPort, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CServerPort, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CServerPort));
  CAlarmInfo_descriptor_ = file->message_type(2);
  static const int CAlarmInfo_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmInfo, ulalarmid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmInfo, ulalarmlevel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmInfo, bbootfilter_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmInfo, ulaftertreatway_),
  };
  CAlarmInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CAlarmInfo_descriptor_,
      CAlarmInfo::default_instance_,
      CAlarmInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CAlarmInfo));
  CAlarmList_descriptor_ = file->message_type(3);
  static const int CAlarmList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmList, data_),
  };
  CAlarmList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CAlarmList_descriptor_,
      CAlarmList::default_instance_,
      CAlarmList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CAlarmList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CAlarmList));
  CCompInfo_descriptor_ = file->message_type(4);
  static const int CCompInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CCompInfo, location_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CCompInfo, dir_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CCompInfo, step_),
  };
  CCompInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CCompInfo_descriptor_,
      CCompInfo::default_instance_,
      CCompInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CCompInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CCompInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CCompInfo));
  CMcu_descriptor_ = file->message_type(5);
  static const int CMcu_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcu, subsysid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcu, comptype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcu, comps_),
  };
  CMcu_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CMcu_descriptor_,
      CMcu::default_instance_,
      CMcu_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcu, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcu, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CMcu));
  CMcuList_descriptor_ = file->message_type(6);
  static const int CMcuList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcuList, data_),
  };
  CMcuList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CMcuList_descriptor_,
      CMcuList::default_instance_,
      CMcuList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcuList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMcuList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CMcuList));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_compensation_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CBackLog_descriptor_, &CBackLog::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CServerPort_descriptor_, &CServerPort::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CAlarmInfo_descriptor_, &CAlarmInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CAlarmList_descriptor_, &CAlarmList::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CCompInfo_descriptor_, &CCompInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CMcu_descriptor_, &CMcu::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CMcuList_descriptor_, &CMcuList::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_compensation_2eproto() {
  delete CBackLog::default_instance_;
  delete CBackLog_reflection_;
  delete CServerPort::default_instance_;
  delete CServerPort_reflection_;
  delete CAlarmInfo::default_instance_;
  delete CAlarmInfo_reflection_;
  delete CAlarmList::default_instance_;
  delete CAlarmList_reflection_;
  delete CCompInfo::default_instance_;
  delete CCompInfo_reflection_;
  delete CMcu::default_instance_;
  delete CMcu_reflection_;
  delete CMcuList::default_instance_;
  delete CMcuList_reflection_;
}

void protobuf_AddDesc_compensation_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022compensation.proto\"!\n\010CBackLog\022\025\n\ruiLo"
    "gBackTime\030\001 \001(\r\"\035\n\013CServerPort\022\016\n\006uiport"
    "\030\001 \001(\r\"c\n\nCAlarmInfo\022\021\n\tulAlarmId\030\001 \001(\r\022"
    "\024\n\014ulAlarmLevel\030\002 \001(\r\022\023\n\013bBootFilter\030\003 \001"
    "(\010\022\027\n\017ulAfterTreatWay\030\004 \001(\r\"\'\n\nCAlarmLis"
    "t\022\031\n\004data\030\001 \003(\0132\013.CAlarmInfo\"8\n\tCCompInf"
    "o\022\020\n\010location\030\001 \001(\r\022\013\n\003dir\030\002 \001(\r\022\014\n\004step"
    "\030\003 \001(\r\"E\n\004CMcu\022\020\n\010subsysid\030\001 \001(\r\022\020\n\010comp"
    "type\030\002 \001(\r\022\031\n\005comps\030\003 \003(\0132\n.CCompInfo\"\037\n"
    "\010CMcuList\022\023\n\004data\030\001 \003(\0132\005.CMcu", 390);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "compensation.proto", &protobuf_RegisterTypes);
  CBackLog::default_instance_ = new CBackLog();
  CServerPort::default_instance_ = new CServerPort();
  CAlarmInfo::default_instance_ = new CAlarmInfo();
  CAlarmList::default_instance_ = new CAlarmList();
  CCompInfo::default_instance_ = new CCompInfo();
  CMcu::default_instance_ = new CMcu();
  CMcuList::default_instance_ = new CMcuList();
  CBackLog::default_instance_->InitAsDefaultInstance();
  CServerPort::default_instance_->InitAsDefaultInstance();
  CAlarmInfo::default_instance_->InitAsDefaultInstance();
  CAlarmList::default_instance_->InitAsDefaultInstance();
  CCompInfo::default_instance_->InitAsDefaultInstance();
  CMcu::default_instance_->InitAsDefaultInstance();
  CMcuList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_compensation_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_compensation_2eproto {
  StaticDescriptorInitializer_compensation_2eproto() {
    protobuf_AddDesc_compensation_2eproto();
  }
} static_descriptor_initializer_compensation_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CBackLog::kUiLogBackTimeFieldNumber;
#endif  // !_MSC_VER

CBackLog::CBackLog()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CBackLog)
}

void CBackLog::InitAsDefaultInstance() {
}

CBackLog::CBackLog(const CBackLog& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CBackLog)
}

void CBackLog::SharedCtor() {
  _cached_size_ = 0;
  uilogbacktime_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CBackLog::~CBackLog() {
  // @@protoc_insertion_point(destructor:CBackLog)
  SharedDtor();
}

void CBackLog::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CBackLog::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CBackLog::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CBackLog_descriptor_;
}

const CBackLog& CBackLog::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_compensation_2eproto();
  return *default_instance_;
}

CBackLog* CBackLog::default_instance_ = NULL;

CBackLog* CBackLog::New() const {
  return new CBackLog;
}

void CBackLog::Clear() {
  uilogbacktime_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CBackLog::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CBackLog)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 uiLogBackTime = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uilogbacktime_)));
          set_has_uilogbacktime();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CBackLog)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CBackLog)
  return false;
#undef DO_
}

void CBackLog::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CBackLog)
  // optional uint32 uiLogBackTime = 1;
  if (has_uilogbacktime()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uilogbacktime(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CBackLog)
}

::google::protobuf::uint8* CBackLog::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CBackLog)
  // optional uint32 uiLogBackTime = 1;
  if (has_uilogbacktime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uilogbacktime(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CBackLog)
  return target;
}

int CBackLog::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 uiLogBackTime = 1;
    if (has_uilogbacktime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->uilogbacktime());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CBackLog::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CBackLog* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CBackLog*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CBackLog::MergeFrom(const CBackLog& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uilogbacktime()) {
      set_uilogbacktime(from.uilogbacktime());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CBackLog::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CBackLog::CopyFrom(const CBackLog& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CBackLog::IsInitialized() const {

  return true;
}

void CBackLog::Swap(CBackLog* other) {
  if (other != this) {
    std::swap(uilogbacktime_, other->uilogbacktime_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CBackLog::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CBackLog_descriptor_;
  metadata.reflection = CBackLog_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CServerPort::kUiportFieldNumber;
#endif  // !_MSC_VER

CServerPort::CServerPort()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CServerPort)
}

void CServerPort::InitAsDefaultInstance() {
}

CServerPort::CServerPort(const CServerPort& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CServerPort)
}

void CServerPort::SharedCtor() {
  _cached_size_ = 0;
  uiport_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CServerPort::~CServerPort() {
  // @@protoc_insertion_point(destructor:CServerPort)
  SharedDtor();
}

void CServerPort::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CServerPort::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CServerPort::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CServerPort_descriptor_;
}

const CServerPort& CServerPort::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_compensation_2eproto();
  return *default_instance_;
}

CServerPort* CServerPort::default_instance_ = NULL;

CServerPort* CServerPort::New() const {
  return new CServerPort;
}

void CServerPort::Clear() {
  uiport_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CServerPort::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CServerPort)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 uiport = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uiport_)));
          set_has_uiport();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CServerPort)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CServerPort)
  return false;
#undef DO_
}

void CServerPort::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CServerPort)
  // optional uint32 uiport = 1;
  if (has_uiport()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uiport(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CServerPort)
}

::google::protobuf::uint8* CServerPort::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CServerPort)
  // optional uint32 uiport = 1;
  if (has_uiport()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uiport(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CServerPort)
  return target;
}

int CServerPort::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 uiport = 1;
    if (has_uiport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->uiport());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CServerPort::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CServerPort* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CServerPort*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CServerPort::MergeFrom(const CServerPort& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uiport()) {
      set_uiport(from.uiport());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CServerPort::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CServerPort::CopyFrom(const CServerPort& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CServerPort::IsInitialized() const {

  return true;
}

void CServerPort::Swap(CServerPort* other) {
  if (other != this) {
    std::swap(uiport_, other->uiport_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CServerPort::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CServerPort_descriptor_;
  metadata.reflection = CServerPort_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CAlarmInfo::kUlAlarmIdFieldNumber;
const int CAlarmInfo::kUlAlarmLevelFieldNumber;
const int CAlarmInfo::kBBootFilterFieldNumber;
const int CAlarmInfo::kUlAfterTreatWayFieldNumber;
#endif  // !_MSC_VER

CAlarmInfo::CAlarmInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CAlarmInfo)
}

void CAlarmInfo::InitAsDefaultInstance() {
}

CAlarmInfo::CAlarmInfo(const CAlarmInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CAlarmInfo)
}

void CAlarmInfo::SharedCtor() {
  _cached_size_ = 0;
  ulalarmid_ = 0u;
  ulalarmlevel_ = 0u;
  bbootfilter_ = false;
  ulaftertreatway_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CAlarmInfo::~CAlarmInfo() {
  // @@protoc_insertion_point(destructor:CAlarmInfo)
  SharedDtor();
}

void CAlarmInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CAlarmInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CAlarmInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CAlarmInfo_descriptor_;
}

const CAlarmInfo& CAlarmInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_compensation_2eproto();
  return *default_instance_;
}

CAlarmInfo* CAlarmInfo::default_instance_ = NULL;

CAlarmInfo* CAlarmInfo::New() const {
  return new CAlarmInfo;
}

void CAlarmInfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CAlarmInfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(ulalarmid_, ulaftertreatway_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CAlarmInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CAlarmInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 ulAlarmId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ulalarmid_)));
          set_has_ulalarmid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_ulAlarmLevel;
        break;
      }

      // optional uint32 ulAlarmLevel = 2;
      case 2: {
        if (tag == 16) {
         parse_ulAlarmLevel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ulalarmlevel_)));
          set_has_ulalarmlevel();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_bBootFilter;
        break;
      }

      // optional bool bBootFilter = 3;
      case 3: {
        if (tag == 24) {
         parse_bBootFilter:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bbootfilter_)));
          set_has_bbootfilter();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_ulAfterTreatWay;
        break;
      }

      // optional uint32 ulAfterTreatWay = 4;
      case 4: {
        if (tag == 32) {
         parse_ulAfterTreatWay:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ulaftertreatway_)));
          set_has_ulaftertreatway();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CAlarmInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CAlarmInfo)
  return false;
#undef DO_
}

void CAlarmInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CAlarmInfo)
  // optional uint32 ulAlarmId = 1;
  if (has_ulalarmid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->ulalarmid(), output);
  }

  // optional uint32 ulAlarmLevel = 2;
  if (has_ulalarmlevel()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->ulalarmlevel(), output);
  }

  // optional bool bBootFilter = 3;
  if (has_bbootfilter()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->bbootfilter(), output);
  }

  // optional uint32 ulAfterTreatWay = 4;
  if (has_ulaftertreatway()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->ulaftertreatway(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CAlarmInfo)
}

::google::protobuf::uint8* CAlarmInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CAlarmInfo)
  // optional uint32 ulAlarmId = 1;
  if (has_ulalarmid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->ulalarmid(), target);
  }

  // optional uint32 ulAlarmLevel = 2;
  if (has_ulalarmlevel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->ulalarmlevel(), target);
  }

  // optional bool bBootFilter = 3;
  if (has_bbootfilter()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->bbootfilter(), target);
  }

  // optional uint32 ulAfterTreatWay = 4;
  if (has_ulaftertreatway()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->ulaftertreatway(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CAlarmInfo)
  return target;
}

int CAlarmInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 ulAlarmId = 1;
    if (has_ulalarmid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->ulalarmid());
    }

    // optional uint32 ulAlarmLevel = 2;
    if (has_ulalarmlevel()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->ulalarmlevel());
    }

    // optional bool bBootFilter = 3;
    if (has_bbootfilter()) {
      total_size += 1 + 1;
    }

    // optional uint32 ulAfterTreatWay = 4;
    if (has_ulaftertreatway()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->ulaftertreatway());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CAlarmInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CAlarmInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CAlarmInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CAlarmInfo::MergeFrom(const CAlarmInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ulalarmid()) {
      set_ulalarmid(from.ulalarmid());
    }
    if (from.has_ulalarmlevel()) {
      set_ulalarmlevel(from.ulalarmlevel());
    }
    if (from.has_bbootfilter()) {
      set_bbootfilter(from.bbootfilter());
    }
    if (from.has_ulaftertreatway()) {
      set_ulaftertreatway(from.ulaftertreatway());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CAlarmInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CAlarmInfo::CopyFrom(const CAlarmInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CAlarmInfo::IsInitialized() const {

  return true;
}

void CAlarmInfo::Swap(CAlarmInfo* other) {
  if (other != this) {
    std::swap(ulalarmid_, other->ulalarmid_);
    std::swap(ulalarmlevel_, other->ulalarmlevel_);
    std::swap(bbootfilter_, other->bbootfilter_);
    std::swap(ulaftertreatway_, other->ulaftertreatway_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CAlarmInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CAlarmInfo_descriptor_;
  metadata.reflection = CAlarmInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CAlarmList::kDataFieldNumber;
#endif  // !_MSC_VER

CAlarmList::CAlarmList()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CAlarmList)
}

void CAlarmList::InitAsDefaultInstance() {
}

CAlarmList::CAlarmList(const CAlarmList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CAlarmList)
}

void CAlarmList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CAlarmList::~CAlarmList() {
  // @@protoc_insertion_point(destructor:CAlarmList)
  SharedDtor();
}

void CAlarmList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CAlarmList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CAlarmList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CAlarmList_descriptor_;
}

const CAlarmList& CAlarmList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_compensation_2eproto();
  return *default_instance_;
}

CAlarmList* CAlarmList::default_instance_ = NULL;

CAlarmList* CAlarmList::New() const {
  return new CAlarmList;
}

void CAlarmList::Clear() {
  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CAlarmList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CAlarmList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CAlarmInfo data = 1;
      case 1: {
        if (tag == 10) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_data;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CAlarmList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CAlarmList)
  return false;
#undef DO_
}

void CAlarmList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CAlarmList)
  // repeated .CAlarmInfo data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->data(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CAlarmList)
}

::google::protobuf::uint8* CAlarmList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CAlarmList)
  // repeated .CAlarmInfo data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->data(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CAlarmList)
  return target;
}

int CAlarmList::ByteSize() const {
  int total_size = 0;

  // repeated .CAlarmInfo data = 1;
  total_size += 1 * this->data_size();
  for (int i = 0; i < this->data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->data(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CAlarmList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CAlarmList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CAlarmList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CAlarmList::MergeFrom(const CAlarmList& from) {
  GOOGLE_CHECK_NE(&from, this);
  data_.MergeFrom(from.data_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CAlarmList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CAlarmList::CopyFrom(const CAlarmList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CAlarmList::IsInitialized() const {

  return true;
}

void CAlarmList::Swap(CAlarmList* other) {
  if (other != this) {
    data_.Swap(&other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CAlarmList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CAlarmList_descriptor_;
  metadata.reflection = CAlarmList_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CCompInfo::kLocationFieldNumber;
const int CCompInfo::kDirFieldNumber;
const int CCompInfo::kStepFieldNumber;
#endif  // !_MSC_VER

CCompInfo::CCompInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CCompInfo)
}

void CCompInfo::InitAsDefaultInstance() {
}

CCompInfo::CCompInfo(const CCompInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CCompInfo)
}

void CCompInfo::SharedCtor() {
  _cached_size_ = 0;
  location_ = 0u;
  dir_ = 0u;
  step_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CCompInfo::~CCompInfo() {
  // @@protoc_insertion_point(destructor:CCompInfo)
  SharedDtor();
}

void CCompInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CCompInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CCompInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CCompInfo_descriptor_;
}

const CCompInfo& CCompInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_compensation_2eproto();
  return *default_instance_;
}

CCompInfo* CCompInfo::default_instance_ = NULL;

CCompInfo* CCompInfo::New() const {
  return new CCompInfo;
}

void CCompInfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CCompInfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(location_, step_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CCompInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CCompInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 location = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &location_)));
          set_has_location();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_dir;
        break;
      }

      // optional uint32 dir = 2;
      case 2: {
        if (tag == 16) {
         parse_dir:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dir_)));
          set_has_dir();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_step;
        break;
      }

      // optional uint32 step = 3;
      case 3: {
        if (tag == 24) {
         parse_step:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &step_)));
          set_has_step();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CCompInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CCompInfo)
  return false;
#undef DO_
}

void CCompInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CCompInfo)
  // optional uint32 location = 1;
  if (has_location()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->location(), output);
  }

  // optional uint32 dir = 2;
  if (has_dir()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dir(), output);
  }

  // optional uint32 step = 3;
  if (has_step()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->step(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CCompInfo)
}

::google::protobuf::uint8* CCompInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CCompInfo)
  // optional uint32 location = 1;
  if (has_location()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->location(), target);
  }

  // optional uint32 dir = 2;
  if (has_dir()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dir(), target);
  }

  // optional uint32 step = 3;
  if (has_step()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->step(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CCompInfo)
  return target;
}

int CCompInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 location = 1;
    if (has_location()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->location());
    }

    // optional uint32 dir = 2;
    if (has_dir()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->dir());
    }

    // optional uint32 step = 3;
    if (has_step()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->step());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CCompInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CCompInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CCompInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CCompInfo::MergeFrom(const CCompInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_location()) {
      set_location(from.location());
    }
    if (from.has_dir()) {
      set_dir(from.dir());
    }
    if (from.has_step()) {
      set_step(from.step());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CCompInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CCompInfo::CopyFrom(const CCompInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CCompInfo::IsInitialized() const {

  return true;
}

void CCompInfo::Swap(CCompInfo* other) {
  if (other != this) {
    std::swap(location_, other->location_);
    std::swap(dir_, other->dir_);
    std::swap(step_, other->step_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CCompInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CCompInfo_descriptor_;
  metadata.reflection = CCompInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CMcu::kSubsysidFieldNumber;
const int CMcu::kComptypeFieldNumber;
const int CMcu::kCompsFieldNumber;
#endif  // !_MSC_VER

CMcu::CMcu()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CMcu)
}

void CMcu::InitAsDefaultInstance() {
}

CMcu::CMcu(const CMcu& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CMcu)
}

void CMcu::SharedCtor() {
  _cached_size_ = 0;
  subsysid_ = 0u;
  comptype_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMcu::~CMcu() {
  // @@protoc_insertion_point(destructor:CMcu)
  SharedDtor();
}

void CMcu::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CMcu::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMcu::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMcu_descriptor_;
}

const CMcu& CMcu::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_compensation_2eproto();
  return *default_instance_;
}

CMcu* CMcu::default_instance_ = NULL;

CMcu* CMcu::New() const {
  return new CMcu;
}

void CMcu::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CMcu*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(subsysid_, comptype_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  comps_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CMcu::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CMcu)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 subsysid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &subsysid_)));
          set_has_subsysid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_comptype;
        break;
      }

      // optional uint32 comptype = 2;
      case 2: {
        if (tag == 16) {
         parse_comptype:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &comptype_)));
          set_has_comptype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_comps;
        break;
      }

      // repeated .CCompInfo comps = 3;
      case 3: {
        if (tag == 26) {
         parse_comps:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_comps()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_comps;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CMcu)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CMcu)
  return false;
#undef DO_
}

void CMcu::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CMcu)
  // optional uint32 subsysid = 1;
  if (has_subsysid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->subsysid(), output);
  }

  // optional uint32 comptype = 2;
  if (has_comptype()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->comptype(), output);
  }

  // repeated .CCompInfo comps = 3;
  for (int i = 0; i < this->comps_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->comps(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CMcu)
}

::google::protobuf::uint8* CMcu::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMcu)
  // optional uint32 subsysid = 1;
  if (has_subsysid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->subsysid(), target);
  }

  // optional uint32 comptype = 2;
  if (has_comptype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->comptype(), target);
  }

  // repeated .CCompInfo comps = 3;
  for (int i = 0; i < this->comps_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->comps(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMcu)
  return target;
}

int CMcu::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 subsysid = 1;
    if (has_subsysid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->subsysid());
    }

    // optional uint32 comptype = 2;
    if (has_comptype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->comptype());
    }

  }
  // repeated .CCompInfo comps = 3;
  total_size += 1 * this->comps_size();
  for (int i = 0; i < this->comps_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->comps(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMcu::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CMcu* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CMcu*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMcu::MergeFrom(const CMcu& from) {
  GOOGLE_CHECK_NE(&from, this);
  comps_.MergeFrom(from.comps_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_subsysid()) {
      set_subsysid(from.subsysid());
    }
    if (from.has_comptype()) {
      set_comptype(from.comptype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CMcu::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMcu::CopyFrom(const CMcu& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMcu::IsInitialized() const {

  return true;
}

void CMcu::Swap(CMcu* other) {
  if (other != this) {
    std::swap(subsysid_, other->subsysid_);
    std::swap(comptype_, other->comptype_);
    comps_.Swap(&other->comps_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CMcu::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMcu_descriptor_;
  metadata.reflection = CMcu_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CMcuList::kDataFieldNumber;
#endif  // !_MSC_VER

CMcuList::CMcuList()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CMcuList)
}

void CMcuList::InitAsDefaultInstance() {
}

CMcuList::CMcuList(const CMcuList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CMcuList)
}

void CMcuList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMcuList::~CMcuList() {
  // @@protoc_insertion_point(destructor:CMcuList)
  SharedDtor();
}

void CMcuList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CMcuList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMcuList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMcuList_descriptor_;
}

const CMcuList& CMcuList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_compensation_2eproto();
  return *default_instance_;
}

CMcuList* CMcuList::default_instance_ = NULL;

CMcuList* CMcuList::New() const {
  return new CMcuList;
}

void CMcuList::Clear() {
  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CMcuList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CMcuList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CMcu data = 1;
      case 1: {
        if (tag == 10) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_data;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CMcuList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CMcuList)
  return false;
#undef DO_
}

void CMcuList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CMcuList)
  // repeated .CMcu data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->data(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CMcuList)
}

::google::protobuf::uint8* CMcuList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMcuList)
  // repeated .CMcu data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->data(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMcuList)
  return target;
}

int CMcuList::ByteSize() const {
  int total_size = 0;

  // repeated .CMcu data = 1;
  total_size += 1 * this->data_size();
  for (int i = 0; i < this->data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->data(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMcuList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CMcuList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CMcuList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMcuList::MergeFrom(const CMcuList& from) {
  GOOGLE_CHECK_NE(&from, this);
  data_.MergeFrom(from.data_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CMcuList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMcuList::CopyFrom(const CMcuList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMcuList::IsInitialized() const {

  return true;
}

void CMcuList::Swap(CMcuList* other) {
  if (other != this) {
    data_.Swap(&other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CMcuList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMcuList_descriptor_;
  metadata.reflection = CMcuList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
