// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: typedefine.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "typedefine.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* MsgType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ActType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ServerPid_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* CilentPid_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* CupState_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* DevType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* BottleType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ReagDiskType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* SmpDskPos_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* RegDskPos_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MixNdlDskPos_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* TaskResult_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* CollideNdl_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* UpdateResult_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* LiquidDBG_Type_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* FLx_enum_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* FLx_state_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* EN_DilutTaskType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ConsumType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ReactCircle_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ShelfCtrlType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MachUnit_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* SmpNdlPos_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* R1DskPos_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* R2DskPos_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ReagNdlPos_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* IntensifyWashType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_typedefine_2eproto() {
  protobuf_AddDesc_typedefine_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "typedefine.proto");
  GOOGLE_CHECK(file != NULL);
  MsgType_descriptor_ = file->enum_type(0);
  ActType_descriptor_ = file->enum_type(1);
  ServerPid_descriptor_ = file->enum_type(2);
  CilentPid_descriptor_ = file->enum_type(3);
  CupState_descriptor_ = file->enum_type(4);
  DevType_descriptor_ = file->enum_type(5);
  BottleType_descriptor_ = file->enum_type(6);
  ReagDiskType_descriptor_ = file->enum_type(7);
  SmpDskPos_descriptor_ = file->enum_type(8);
  RegDskPos_descriptor_ = file->enum_type(9);
  MixNdlDskPos_descriptor_ = file->enum_type(10);
  TaskResult_descriptor_ = file->enum_type(11);
  CollideNdl_descriptor_ = file->enum_type(12);
  UpdateResult_descriptor_ = file->enum_type(13);
  LiquidDBG_Type_descriptor_ = file->enum_type(14);
  FLx_enum_descriptor_ = file->enum_type(15);
  FLx_state_descriptor_ = file->enum_type(16);
  EN_DilutTaskType_descriptor_ = file->enum_type(17);
  ConsumType_descriptor_ = file->enum_type(18);
  ReactCircle_descriptor_ = file->enum_type(19);
  ShelfCtrlType_descriptor_ = file->enum_type(20);
  MachUnit_descriptor_ = file->enum_type(21);
  SmpNdlPos_descriptor_ = file->enum_type(22);
  R1DskPos_descriptor_ = file->enum_type(23);
  R2DskPos_descriptor_ = file->enum_type(24);
  ReagNdlPos_descriptor_ = file->enum_type(25);
  IntensifyWashType_descriptor_ = file->enum_type(26);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_typedefine_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_typedefine_2eproto() {
}

void protobuf_AddDesc_typedefine_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020typedefine.proto*\270\020\n\007MsgType\022\021\n\014MSG_Re"
    "qReset\020\321\017\022\021\n\014MSG_ResReset\020\322\017\022\023\n\016MSG_ReqA"
    "ddTask\020\323\017\022\023\n\016MSG_ResAddTask\020\324\017\022\034\n\027MSG_No"
    "tifyMachineStatus\020\325\017\022\033\n\026MSG_NotifyRctCup"
    "Status\020\326\017\022\026\n\021MSG_ReqMarginScan\020\327\017\022\026\n\021MSG"
    "_ResMarginScan\020\330\017\022\027\n\022MSG_ReqBarcodeScan\020"
    "\331\017\022\027\n\022MSG_ResBarcodeScan\020\332\017\022\022\n\rMSG_ReqAi"
    "rOut\020\333\017\022\024\n\017MSG_NotifyTimer\020\334\017\022\032\n\025MSG_Req"
    "ReagentSuspend\020\335\017\022\026\n\021MSG_AckTaskResult\020\336"
    "\017\022\031\n\024MSG_ReqIntensifyWash\020\337\017\022\033\n\026MSG_Noti"
    "fyReportResult\020\340\017\022\027\n\022MSG_NotifyReagInfo\020"
    "\341\017\022\021\n\014MSG_WriteLog\020\342\017\022\026\n\021MSG_NotifyADVal"
    "ue\020\343\017\022\026\n\021MSG_NotifyConnect\020\344\017\022\021\n\014MSG_Req"
    "Hello\020\345\017\022\021\n\014MSG_ResHello\020\346\017\022\022\n\rMSG_ReqAc"
    "tCmd\020\347\017\022\025\n\020MSG_NotifyOffset\020\350\017\022\024\n\017MSG_Re"
    "qStopMach\020\351\017\022\026\n\021MSG_ReqPreciseAdd\020\352\017\022\026\n\021"
    "MSG_ReqLightCheck\020\353\017\022\024\n\017MSG_ReqCupBlank\020"
    "\354\017\022\030\n\023MSG_ReqWashReactCup\020\355\017\022\023\n\016MSG_ReqS"
    "etTime\020\356\017\022\027\n\022MSG_ReqDarkCurrent\020\360\017\022\027\n\022MS"
    "G_ResDarkCurrent\020\361\017\022\023\n\016MSG_NotifyTemp\020\363\017"
    "\022\022\n\rMSG_GetMidLog\020\364\017\022\031\n\024MSG_CollideNdlCo"
    "nfig\020\365\017\022\020\n\013MSG_GetVres\020\366\017\022\020\n\013MSG_ResVres"
    "\020\367\017\022\034\n\027MSG_NotifyFailedSmpTask\020\370\017\022\024\n\017MSG"
    "_ReqCompBack\020\371\017\022\024\n\017MSG_ResCompBack\020\372\017\022\027\n"
    "\022MSG_ReqCompRecover\020\373\017\022\027\n\022MSG_ResCompRec"
    "over\020\374\017\022\024\n\017MSG_NotifyAlarm\020\375\017\022\027\n\022MSG_Not"
    "ifySynAlarm\020\376\017\022\027\n\022MSG_ReqDeleteAlarm\020\377\017\022"
    "\027\n\022MSG_NotifySendTask\020\201\020\022\023\n\016MSG_TempeQue"
    "ry\020\202\020\022\022\n\rMSG_UpdateDwn\020\203\020\022\032\n\025MSG_ReqSmoo"
    "thAreaTest\020\204\020\022\032\n\025MSG_ResSmoothAreaTest\020\205"
    "\020\022\024\n\017MSG_ReqShowWave\020\206\020\022\024\n\017MSG_ResShowWa"
    "ve\020\207\020\022\027\n\022MSG_ReqConnectPort\020\210\020\022\017\n\nMSG_AD"
    "test\020\211\020\022\024\n\017MSG_NotifyMotor\020\212\020\022\027\n\022MSG_Req"
    "BackupMotor\020\213\020\022\027\n\022MSG_ResBackupMotor\020\214\020\022"
    "\030\n\023MSG_ReqRecoverMotor\020\215\020\022\030\n\023MSG_ReqRegP"
    "ollution\020\216\020\022\030\n\023MSG_ReqSmpPollution\020\217\020\022\025\n"
    "\020MSG_ReqBeepAlarm\020\220\020\022\030\n\023MSG_ReqRctPollut"
    "ion\020\221\020\022\020\n\013MSG_Consume\020\222\020\022\016\n\tMSG_CPUID\020\223\020"
    "\022\021\n\014MSG_ReqShelf\020\224\020\022\021\n\014MSG_ResShelf\020\225\020\022\021"
    "\n\014MSG_SetShelf\020\226\020\022\024\n\017MSG_NotifyState\020\227\020\022"
    "\022\n\rMSG_FreeShelf\020\230\020\022\035\n\030MSG_NotifySmpFram"
    "eStatus\020\231\020\022\031\n\024MSG_NotifyReagChange\020\232\020\022\022\n"
    "\rMSG_ReqShowAD\020\302\027\022\022\n\rMSG_ResShowAD\020\303\027\022\021\n"
    "\014MSG_FLXQuery\020\304\027\022\033\n\026MSG_ReqReadDarkCurre"
    "nt\020\305\027\022\033\n\026MSG_ResReadDarkCurrent\020\306\027\022\035\n\030MS"
    "G_NotifyTestingADValue\020\307\027\022\023\n\016MSG_ReqSkip"
    "Cup\020\310\027\022\021\n\014MSG_SetSleep\020\311\027\022\024\n\017MSG_NotifyS"
    "ound\020\312\027\022\026\n\021MSG_CfgAlarmSound\020\313\027\022\024\n\017MSG_R"
    "eqBeepPlay\020\314\027\022\021\n\014MSG_TestOver\020\315\027\022\024\n\017MSG_"
    "BloodAbsorb\020\316\027\022\021\n\014MSG_TempPara\020\317\027\022\026\n\021MSG"
    "_AutoloadDebug\020\320\027\022\027\n\022MSG_AutoLoadStatus\020"
    "\321\027\022\027\n\022MSG_ReqAutoPowerOn\020\334\027\022\033\n\026MSG_ReqAu"
    "toPowerOnInfo\020\335\027\022\033\n\026MSG_ResAutoPowerOnIn"
    "fo\020\336\027*\232\013\n\007ActType\022\r\n\tAct_Reset\020\000\022\014\n\010Act_"
    "Move\020\001\022\016\n\nAct_Absorb\020\002\022\021\n\rAct_Discharge\020"
    "\003\022\014\n\010Act_Wash\020\004\022\016\n\nAct_AirOut\020\005\022\013\n\007Act_M"
    "ix\020\006\022\025\n\021Act_IntensifyWash\020\007\022\016\n\nAct_BcSca"
    "n\020\010\022\020\n\014Act_DwnQuery\020\t\022\022\n\016Act_TrimOffset\020"
    "\n\022\022\n\016Act_SaveOffset\020\013\022\016\n\nAct_NdlVrt\020\014\022\r\n"
    "\tAct_Light\020\r\022\n\n\006Act_Ad\020\016\022\022\n\016Act_DskHrota"
    "te\020\017\022\022\n\016Act_MarginScan\020\020\022\022\n\016Act_TempSwit"
    "ch\020\021\022\r\n\tAct_Fault\020\022\022\r\n\tAct_Debug\020\023\022\021\n\rAc"
    "t_TempQuery\020\024\022\017\n\013Act_CtrlP04\020\025\022\020\n\014Act_Mi"
    "dState\020\026\022\016\n\nAct_PVCtrl\020\027\022\020\n\014Act_PumpCtrl"
    "\020\030\022\024\n\020Act_LiquidsCheck\020\031\022\023\n\017Act_CoolingC"
    "trl\020\032\022\017\n\013Act_BBClear\020\033\022\024\n\020Act_SmpLightCt"
    "rl\020\034\022\021\n\rAct_UpdateDwn\020\035\022\017\n\013Act_OlnyMix\020\036"
    "\022\017\n\013Act_Showave\020\037\022\021\n\rAct_LiquidDBG\020 \022\022\n\016"
    "Act_SetFlState\020!\022\022\n\016Act_WriteMotor\020\"\022\020\n\014"
    "Act_MoveDilu\020#\022\022\n\016Act_AbsorbDilu\020$\022\025\n\021Ac"
    "t_DischargeDilu\020%\022\022\n\016Act_UpdateFpga\020&\022\020\n"
    "\014Act_sleepCtl\020\'\022\020\n\014Act_washLong\020(\022\021\n\rAct"
    "_washShort\020)\022\020\n\014Act_SetWTemp\020*\022\020\n\014Act_Se"
    "tRTemp\020+\022\r\n\tAct_Timer\020,\022\017\n\013Act_MoveAbs\020-"
    "\022\r\n\tAct_MoveW\020.\022\021\n\rAct_MoveInner\020/\022\021\n\rAc"
    "t_MoveOuter\0200\022\r\n\tAct_OneAD\0201\022\017\n\013Act_SetG"
    "ain\0202\022\020\n\014Act_GetShelf\0203\022\021\n\rAct_FreeShelf"
    "\0204\022\020\n\014Act_MoveDisg\0205\022\r\n\tAct_GetIn\0206\022\023\n\017A"
    "ct_FreeShelfIn\0207\022\023\n\017Act_StateSwitch\0208\022\023\n"
    "\017Act_TempControl\0209\022\020\n\014Act_GwPushIn\020d\022\023\n\017"
    "Act_GwShelfScan\020e\022\023\n\017Act_GwScheduGet\020h\022\023"
    "\n\017Act_GwScheduPut\020i\022\023\n\017Act_GwTransNorm\020j"
    "\022\023\n\017Act_GwTransEmer\020k\022\021\n\rAct_GwFreeGet\020l"
    "\022\021\n\rAct_GwFreePop\020m\022\021\n\rAct_GwRecycle\020o\022\022"
    "\n\016Act_GwFreeRecy\020p\022\021\n\rAct_GwPushOut\020q\022\023\n"
    "\017Act_GwChangNorm\020r\022\023\n\017Act_GwChangEmer\020s\022"
    "\023\n\017Act_GwChangRecy\020t\022\017\n\013Act_TPMoveL\020x\022\017\n"
    "\013Act_TPMoveF\020y\022\017\n\013Act_TPMoveR\020z\022\017\n\013Act_V"
    "GMoveL\020{\022\017\n\013Act_VGMoveF\020|\022\017\n\013Act_VGMoveR"
    "\020}*\247\010\n\tServerPid\022\027\n\022SPid_SocketMonitor\020\221"
    "\003\022\020\n\013SPid_Oammng\020\375\003\022\020\n\013SPid_BcScan\020\376\003\022\022\n"
    "\rSPid_Maintain\020\210\004\022\027\n\022SPid_CheckLightCup\020"
    "\222\004\022\025\n\020SPid_DarkCurrent\020\234\004\022\017\n\nSPid_Alarm\020"
    "\246\004\022\023\n\016Spid_UpdateDwn\020\260\004\022\021\n\014SPid_Showave\020"
    "\272\004\022\020\n\013SPid_Smooth\020\304\004\022\020\n\013SPid_ShowAD\020\316\004\022\016"
    "\n\tSPid_Task\020\275\005\022\024\n\017SPid_MarginScan\020\277\005\022\020\n\013"
    "SPid_AirOut\020\300\005\022\027\n\022SPid_IntensifyWash\020\301\005\022"
    "\017\n\nSPid_Reset\020\302\005\022\020\n\013SPid_DwnCmd\020\303\005\022\024\n\017SP"
    "id_PreciseAdd\020\304\005\022\023\n\016SPid_TmpSwitch\020\305\005\022\020\n"
    "\013SPid_SmpNdl\020\205\007\022\021\n\014SPid_SmpNdlb\020\206\007\022\022\n\rSP"
    "id_ReactDsk\020\207\007\022\022\n\rSPid_AutoWash\020\210\007\022\016\n\tSP"
    "id_SMix\020\211\007\022\017\n\nSPid_R2Mix\020\212\007\022\014\n\007SPid_R1\020\213"
    "\007\022\017\n\nSPid_R1Dsk\020\214\007\022\r\n\010SPid_R1b\020\215\007\022\014\n\007SPi"
    "d_R2\020\216\007\022\017\n\nSPid_R2Dsk\020\217\007\022\r\n\010SPid_R2b\020\220\007\022"
    "\022\n\rSPid_RTmpCtrl\020\221\007\022\022\n\rSPid_WTmpCtrl\020\222\007\022"
    "\022\n\rSPid_CoolReag\020\223\007\022\021\n\014SPid_ADOuter\020\224\007\022\021"
    "\n\014SPid_ADInner\020\225\007\022\020\n\013SPid_SmpDsk\020\227\007\022\021\n\014S"
    "Pid_SmpEmer\020\230\007\022\017\n\nSPid_Press\020\231\007\022\021\n\014SPid_"
    "TmpCtrl\020\232\007\022\025\n\020SPid_AutoPowerOn\020\235\007\022\017\n\nSPi"
    "d_Light\020\236\007\022\014\n\007SPid_31\020\243\007\022\014\n\007SPid_32\020\244\007\022\014"
    "\n\007SPid_33\020\245\007\022\014\n\007SPid_34\020\246\007\022\014\n\007SPid_35\020\247\007"
    "\022\014\n\007SPid_36\020\250\007\022\014\n\007SPid_37\020\251\007\022\014\n\007SPid_38\020"
    "\252\007\022\014\n\007SPid_39\020\253\007\022\014\n\007SPid_40\020\254\007\022\022\n\rSPid_A"
    "utoLoad\020\266\007\022\023\n\016SPid_Transport\020\267\007\022\031\n\024SPid_"
    "VerticalGripper\020\270\007\022\014\n\007SPid_L1\020\271\007\022\014\n\007SPid"
    "_L2\020\272\007\022\024\n\017SPid_TaskResult\020\351\007*\224\002\n\tCilentP"
    "id\022\027\n\022CPid_SocketMonitor\020\222\003\022\025\n\020GPid_Gway"
    "Monitor\020\223\003\022\021\n\014CPid_Reagent\020\370\003\022\032\n\025CPid_Re"
    "actDiskMonitor\020\374\003\022\022\n\rCPid_Maintain\020\376\003\022\017\n"
    "\nCPid_Alarm\020\201\004\022\017\n\nCPid_Sound\020\202\004\022\020\n\013CPid_"
    "OffSet\020\210\004\022\020\n\013CPid_Consum\020\222\004\022\022\n\rCPid_Rela"
    "tion\020\234\004\022\021\n\014CPid_SmpTask\020\205\007\022\023\n\016CPid_Calib"
    "rate\020\207\007\022\022\n\rCPid_SendTask\020\351\007*\321\001\n\010CupState"
    "\022\022\n\016CUP_STATE_FREE\020\000\022\022\n\016CUP_STATE_WASH\020\001"
    "\022\020\n\014CUP_STATE_R1\020\002\022\024\n\020CUP_STATE_SAMPLE\020\003"
    "\022\020\n\014CUP_STATE_R2\020\004\022\020\n\014CUP_STATE_R3\020\005\022\020\n\014"
    "CUP_STATE_R4\020\006\022\026\n\022CUP_STATE_REACTION\020\007\022\023"
    "\n\017CUP_STATE_DIRTY\020\010\022\022\n\016CUP_STATE_BUTT\020\t*"
    ".\n\007DevType\022\r\n\tSampleNdl\020\000\022\t\n\005R1Ndl\020\001\022\t\n\005"
    "R2Ndl\020\002*:\n\nBottleType\022\017\n\013BT_standard\020\002\022\014"
    "\n\010BT_micro\020\001\022\r\n\tBT_middle\020\003*;\n\014ReagDiskT"
    "ype\022\024\n\020ReagDisk_Default\020\001\022\025\n\021ReagDisk_Au"
    "toLoad\020\002*\304\001\n\tSmpDskPos\022\020\n\014SmpPosAbsrb1\020\000"
    "\022\020\n\014SmpPosAbsrb2\020\001\022\020\n\014SmpPosAbsrb3\020\002\022\020\n\014"
    "SmpPosAbsrb4\020\003\022\020\n\014SmpPosAbsrb5\020\004\022\016\n\nSmpP"
    "osWash\020\005\022\023\n\017SmpPosRailAbsrb\020\006\022\020\n\014SmpPosD"
    "ilute\020\007\022\022\n\016SmpPosDischNml\020\010\022\022\n\016SmpPosDis"
    "chISE\020\t*C\n\tRegDskPos\022\017\n\013RegPossWash\020\000\022\020\n"
    "\014RegPossAbsrb\020\001\022\023\n\017RegPossDischarg\020\002*L\n\014"
    "MixNdlDskPos\022\017\n\013MixPossWash\020\000\022\r\n\tMixPoss"
    "33\020\001\022\r\n\tMixPoss38\020\002\022\r\n\tMixPoss67\020\003*\343\001\n\nT"
    "askResult\022\016\n\nTR_Success\020\000\022\017\n\013TR_SysFault"
    "\020\001\022\016\n\nTR_ReagErr\020\002\022\017\n\013TR_GetADErr\020\003\022\017\n\013T"
    "R_AddR1Err\020\004\022\017\n\013TR_AddR2Err\020\005\022\017\n\013TR_AddR"
    "3Err\020\006\022\017\n\013TR_AddR4Err\020\007\022\020\n\014TR_AddSmpErr\020"
    "\010\022\021\n\rTR_UserCancel\020\t\022\r\n\tTR_NetErr\020\n\022\016\n\nT"
    "R_DilOver\020\013\022\013\n\007TR_Skip\020\014*D\n\nCollideNdl\022\020"
    "\n\014collide_stop\020\001\022\022\n\016collide_cancel\020\002\022\020\n\014"
    "collide_null\020\003*F\n\014UpdateResult\022\016\n\nUR_suc"
    "cess\020\000\022\r\n\tUR_failed\020\001\022\n\n\006UR_ing\020\002\022\013\n\007UR_"
    "stop\020\003*\265\007\n\016LiquidDBG_Type\022\034\n\030app_deion_p"
    "ipe_flood_req\020\001\022\032\n\026app_smp_pipe_flood_re"
    "q\020\002\022\031\n\025app_r1_pipe_flood_req\020\003\022\031\n\025app_r2"
    "_pipe_flood_req\020\004\022\032\n\026app_complete_drain_"
    "req\020\005\022\027\n\023app_add_smponly_req\020\006\022\026\n\022app_ad"
    "d_r1only_req\020\007\022\026\n\022app_add_r2only_req\020\010\022\031"
    "\n\025app_drain_smponly_req\020\t\022\030\n\024app_drain_r"
    "1only_req\020\n\022\030\n\024app_drain_r2only_req\020\013\022\031\n"
    "\025app_drain_add_smp_req\020\014\022\030\n\024app_drain_ad"
    "d_r1_req\020\r\022\030\n\024app_drain_add_r2_req\020\016\022\034\n\030"
    "app_auto_wash_test_2_req\020\017\022\034\n\030app_auto_w"
    "ash_test_3_req\020\020\022\034\n\030app_auto_wash_test_4"
    "_req\020\021\022\034\n\030app_auto_wash_test_6_req\020\022\022\035\n\031"
    "app_auto_wash_test_71_req\020\023\022\035\n\031app_auto_"
    "wash_test_72_req\020\024\022!\n\035app_auto_wash_clos"
    "e_allPV_req\020\025\022\016\n\nwashDBG_WR\020\026\022\016\n\nwashDBG"
    "_WW\020\027\022\020\n\014washDBG_OMVA\020\030\022\020\n\014washDBG_CMVA\020"
    "\031\022\024\n\020app_accuracyAddS\020\032\022\025\n\021app_accuracyA"
    "ddR1\020\033\022\025\n\021app_accuracyAddR2\020\034\022\024\n\020app_acc"
    "uracyRMix\020\035\022\024\n\020app_accuracySMix\020\036\022\033\n\027app"
    "_smpb_pipe_flood_req\020\037\022\032\n\026app_r1b_pipe_f"
    "lood_req\020 \022\032\n\026app_r2b_pipe_flood_req\020!\022\025"
    "\n\021app_drain_add_req\020\"\022\017\n\013app_add_req\020#\022\021"
    "\n\rapp_drain_req\020$\022\023\n\017app_accuracyAdd\020%*\252"
    "\001\n\010FLx_enum\022\014\n\010FL01_low\020\000\022\r\n\tFL01_high\020\001"
    "\022\014\n\010FL05_low\020\002\022\r\n\tFL05_high\020\003\022\014\n\010FL06_lo"
    "w\020\004\022\r\n\tFL06_high\020\005\022\010\n\004FL10\020\006\022\010\n\004FL11\020\007\022\010"
    "\n\004FL12\020\010\022\010\n\004FL13\020\t\022\010\n\004FL14\020\n\022\t\n\005FLise\020\013\022"
    "\n\n\006FLiseB\020\014*3\n\tFLx_state\022\n\n\006FLX_ON\020\000\022\013\n\007"
    "FLX_OFF\020\001\022\r\n\010FLx_idll\020\377\001*K\n\020EN_DilutTask"
    "Type\022\020\n\014EN_DilutNorm\020\000\022\020\n\014EN_DilutType\020\001"
    "\022\023\n\017EN_ReactionType\020\002*-\n\nConsumType\022\016\n\tC"
    "sum_Wash\020\346\007\022\017\n\nCsum_Ligth\020\347\007*A\n\013ReactCir"
    "cle\022\016\n\nCircle_All\020\000\022\020\n\014Circle_Outer\020\001\022\020\n"
    "\014Circle_Inner\020\002*=\n\rShelfCtrlType\022\r\n\tShel"
    "f_Req\020\001\022\r\n\tShelf_Res\020\002\022\016\n\nShelf_Free\020\003*Z"
    "\n\010MachUnit\022\r\n\tUnit_Gway\020\000\022\013\n\007Unit_A1\020\001\022\013"
    "\n\007Unit_A2\020\002\022\013\n\007Unit_A3\020\003\022\013\n\007Unit_A4\020\004\022\013\n"
    "\007Unit_UI\020\005*\224\001\n\tSmpNdlPos\022\021\n\rSNdlPosDilut"
    "e\020\000\022\023\n\017SNdlPosDischarg\020\001\022\020\n\014SNdlPosReset"
    "\020\002\022\r\n\tSNdlPosW1\020\003\022\r\n\tSNdlPosW2\020\004\022\r\n\tSNdl"
    "PosW3\020\005\022\017\n\013SNdlPosEmer\020\006\022\017\n\013SNdlPosNorm\020"
    "\007*Z\n\010R1DskPos\022\022\n\016R1DskPosouter1\020\001\022\022\n\016R1D"
    "skPosouter2\020\007\022\022\n\016R1DskPosInner1\020\n\022\022\n\016R1D"
    "skPosInner2\020\004*Z\n\010R2DskPos\022\022\n\016R2DskPosout"
    "er1\020\001\022\022\n\016R2DskPosouter2\020\t\022\022\n\016R2DskPosInn"
    "er1\020\014\022\022\n\016R2DskPosInner2\020\004*\210\001\n\nReagNdlPos"
    "\022\023\n\017RNdlPosDischarg\020\001\022\020\n\014RNdlPosReset\020\002\022"
    "\r\n\tRNdlPosW1\020\003\022\r\n\tRNdlPosW2\020\004\022\r\n\tRNdlPos"
    "W3\020\005\022\022\n\016RNdlPosAbsorb1\020\006\022\022\n\016RNdlPosAbsor"
    "b2\020\007*`\n\021IntensifyWashType\022\025\n\021IntensifyWa"
    "shAcid\020\001\022\027\n\023IntensifyWashAlkali\020\002\022\033\n\027Int"
    "ensifyWashAcidAlkali\020\003", 8102);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "typedefine.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_typedefine_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_typedefine_2eproto {
  StaticDescriptorInitializer_typedefine_2eproto() {
    protobuf_AddDesc_typedefine_2eproto();
  }
} static_descriptor_initializer_typedefine_2eproto_;
const ::google::protobuf::EnumDescriptor* MsgType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgType_descriptor_;
}
bool MsgType_IsValid(int value) {
  switch(value) {
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 2008:
    case 2009:
    case 2010:
    case 2011:
    case 2012:
    case 2013:
    case 2014:
    case 2015:
    case 2016:
    case 2017:
    case 2018:
    case 2019:
    case 2020:
    case 2021:
    case 2022:
    case 2023:
    case 2024:
    case 2025:
    case 2026:
    case 2027:
    case 2028:
    case 2029:
    case 2030:
    case 2032:
    case 2033:
    case 2035:
    case 2036:
    case 2037:
    case 2038:
    case 2039:
    case 2040:
    case 2041:
    case 2042:
    case 2043:
    case 2044:
    case 2045:
    case 2046:
    case 2047:
    case 2049:
    case 2050:
    case 2051:
    case 2052:
    case 2053:
    case 2054:
    case 2055:
    case 2056:
    case 2057:
    case 2058:
    case 2059:
    case 2060:
    case 2061:
    case 2062:
    case 2063:
    case 2064:
    case 2065:
    case 2066:
    case 2067:
    case 2068:
    case 2069:
    case 2070:
    case 2071:
    case 2072:
    case 2073:
    case 2074:
    case 3010:
    case 3011:
    case 3012:
    case 3013:
    case 3014:
    case 3015:
    case 3016:
    case 3017:
    case 3018:
    case 3019:
    case 3020:
    case 3021:
    case 3022:
    case 3023:
    case 3024:
    case 3025:
    case 3036:
    case 3037:
    case 3038:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ActType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ActType_descriptor_;
}
bool ActType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 100:
    case 101:
    case 104:
    case 105:
    case 106:
    case 107:
    case 108:
    case 109:
    case 111:
    case 112:
    case 113:
    case 114:
    case 115:
    case 116:
    case 120:
    case 121:
    case 122:
    case 123:
    case 124:
    case 125:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ServerPid_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ServerPid_descriptor_;
}
bool ServerPid_IsValid(int value) {
  switch(value) {
    case 401:
    case 509:
    case 510:
    case 520:
    case 530:
    case 540:
    case 550:
    case 560:
    case 570:
    case 580:
    case 590:
    case 701:
    case 703:
    case 704:
    case 705:
    case 706:
    case 707:
    case 708:
    case 709:
    case 901:
    case 902:
    case 903:
    case 904:
    case 905:
    case 906:
    case 907:
    case 908:
    case 909:
    case 910:
    case 911:
    case 912:
    case 913:
    case 914:
    case 915:
    case 916:
    case 917:
    case 919:
    case 920:
    case 921:
    case 922:
    case 925:
    case 926:
    case 931:
    case 932:
    case 933:
    case 934:
    case 935:
    case 936:
    case 937:
    case 938:
    case 939:
    case 940:
    case 950:
    case 951:
    case 952:
    case 953:
    case 954:
    case 1001:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* CilentPid_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CilentPid_descriptor_;
}
bool CilentPid_IsValid(int value) {
  switch(value) {
    case 402:
    case 403:
    case 504:
    case 508:
    case 510:
    case 513:
    case 514:
    case 520:
    case 530:
    case 540:
    case 901:
    case 903:
    case 1001:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* CupState_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CupState_descriptor_;
}
bool CupState_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* DevType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DevType_descriptor_;
}
bool DevType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* BottleType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BottleType_descriptor_;
}
bool BottleType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ReagDiskType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReagDiskType_descriptor_;
}
bool ReagDiskType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* SmpDskPos_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SmpDskPos_descriptor_;
}
bool SmpDskPos_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RegDskPos_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RegDskPos_descriptor_;
}
bool RegDskPos_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MixNdlDskPos_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MixNdlDskPos_descriptor_;
}
bool MixNdlDskPos_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* TaskResult_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TaskResult_descriptor_;
}
bool TaskResult_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* CollideNdl_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CollideNdl_descriptor_;
}
bool CollideNdl_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* UpdateResult_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UpdateResult_descriptor_;
}
bool UpdateResult_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* LiquidDBG_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LiquidDBG_Type_descriptor_;
}
bool LiquidDBG_Type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* FLx_enum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FLx_enum_descriptor_;
}
bool FLx_enum_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* FLx_state_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FLx_state_descriptor_;
}
bool FLx_state_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 255:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* EN_DilutTaskType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EN_DilutTaskType_descriptor_;
}
bool EN_DilutTaskType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ConsumType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ConsumType_descriptor_;
}
bool ConsumType_IsValid(int value) {
  switch(value) {
    case 998:
    case 999:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ReactCircle_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReactCircle_descriptor_;
}
bool ReactCircle_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ShelfCtrlType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ShelfCtrlType_descriptor_;
}
bool ShelfCtrlType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MachUnit_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MachUnit_descriptor_;
}
bool MachUnit_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* SmpNdlPos_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SmpNdlPos_descriptor_;
}
bool SmpNdlPos_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* R1DskPos_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return R1DskPos_descriptor_;
}
bool R1DskPos_IsValid(int value) {
  switch(value) {
    case 1:
    case 4:
    case 7:
    case 10:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* R2DskPos_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return R2DskPos_descriptor_;
}
bool R2DskPos_IsValid(int value) {
  switch(value) {
    case 1:
    case 4:
    case 9:
    case 12:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ReagNdlPos_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReagNdlPos_descriptor_;
}
bool ReagNdlPos_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* IntensifyWashType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return IntensifyWashType_descriptor_;
}
bool IntensifyWashType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
